project:
  type: website

website:
  title: "DREAM Analytics"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - viz.qmd
      - services.qmd
      - recs.qmd
      - orgs.qmd
      - href: http://www.jamiepantazi.com
        text: Portfolio
format:
  html:
    theme: custom.scss
    toc: true
    link-external-newwindow: true



