---
title: "badmenbib"
editor: visual
---

# Bibliography

## Primary Sources

*24*. Created by Robert Cochran, Joel Surnow. USA: 20th Century Fox Television, 2001-2014.

Birth of a Nation. Directed by D. W. Griffith. Santa Monica, CA: Epoch Producing Corporation, 1915.

Bleecker, Ann Eliza. The History of Maria Kittle. Hartford: Elisha Babcook, 1797. Reprinted New York: Garland Publishing, 1978.

Cooper, James Fenimore. The Last of the Mohicans: A Narrative of 1757. Philadelphia: H.C. Carey & I. Lea, 1826.

Delta Force 2: The Colombian Connection. Directed by Aaron Norris. USA: Cannon Films, 1990.

Dixon, Thomas. The Clansman: An American Drama: From His Two Famous Novels: The Leopards Spots and the Clansman: Presented by the Southern Amusement Co. New York: American News, 1905.

Dixon, Thomas. The Clansman: An Historical Romance of the Ku Klux Klan. New York: Grosset & Dunlap, 1905.

Ellis, Edward Sylvester. Seth Jones: Or, The Captives of the Frontier. New York: Beadle and Adams, 1860.

Gast, John. American Progress. 1872. Chromolithograph published by George A, Crofutt. Prints and Photographs Division, Library of Congress. https://picturinghistory.gc.cuny.edu/john-gast-american-progress-1872/

Iron Man. Directed by Jon Favreau. USA: Paramount / Marvel Studios, 2008.

True Lies. Directed by James Cameron. USA: Twentieth Century Fox, 1994.

United States. Census Office. 11th Census, 1890. Compendium of the Eleventh Census: 1890. By Robert P. Porter. Washington, DC: Govt. Print. Off., 1892.

Vanderlyn, John. The Murder of Jane McCrea. 1804. Wadsworth Atheneum, Hartford. http://www.19thcenturyart-facos.com/artwork/murder-jane-mccrea

## Newspapers

### Atlanta Constitution

"'The Clansman' Not Wanted Here," The Atlanta Constitution. (Atlanta, Georgia) September 27, 1906.

"'The Clansman' on the Stage," The Atlanta Constitution. (Atlanta, Georgia) August 13, 1905.

"The Hissing of the 'Clansman'," The Atlanta Constitution. (Atlanta, Georgia) October 22, 1905.

"Tom Dixon Talks of the Clansman," The Atlanta Constitution. (Atlanta, Georgia) October 29, 1905.

### Daily National Intelligencer

"Generalo Cox, candidate of the Republican party for Governor of Ohio, in reply to a committee, writes a striking letter about the problem of the black race." Daily National Intelligencer (Washington, DC), August 04, 1865.

"Insults and Outrages upon the Women of the South." Daily National Intelligencer. (Washington, DC) October 06, 1868.

"The Negro as Developed by Radical Policy." Daily National Intelligencer (Washington, DC), September 26, 1868

"Western Scenery." Daily National Intelligencer. (Washington, DC) March 08, 1819.

### Other Newspapers:

"Beadle's Dime Novels." Frank Leslie's Illustrated Newspaper (New York, New York) December 8, 1860.

"Burning a Negro Murderer." The Daily Scioto Gazette (Chillicothe, Ohio) August 03, 1853.

"Dime Novels." The Wisconsin State Register. (Portage, Wisconsin) April 26, 1884.

"Literary." The Daily Cleveland Herald. (Cleveland, Ohio) December 07, 1863.

## Secondary Sources

Berkholder, Robert F. The White Man's Indian. New York: Alfred A. Knoff, Inc., 1978.

Davis, Angela. "Rape, Racism, and the Myth of the Black Rapist," Women, Race & Class. New York: Vintage Books, 1981.

Dunbar-Ortiz, Roxanne. An Indigenous Peoples History of the United States. Boston: Beacon Press, 2015.

Godshalk, David Fort. Veiled Visions the 1906 Atlanta Race Riot and the Reshaping of American Race Relations. Chapel Hill: University of North Carolina Press, 2005.

Heymann, Philip B., and Stokes, Melvyn. D. W. Griffith's the Birth of a Nation: A History of the Most Controversial Motion Picture of All Time. Cary: Oxford University Press USA - OSO, 2008.

Lennard, Katherine. "Old Purpose,"New Body": The Birth of a Nation and The Revival Of The Ku Klux Klan." The Journal of the Gilded Age and Progressive Era 14, no. 04 (2015): 616-20.

Macdonald, Andrew, Gina Macdonald, and MaryAnn Sheridan. Shape-shifting: Images of Native Americans in Recent Popular Fiction. Westport, CT: Greenwood Press, 2000.

Nelson, Dana D. National Manhood: Capitalist Citizenship and the Imagined Fraternity of White Men. Durham: Duke University Press, 1998.

Parsons, Elaine Frantz. "Klan Skepticism and Denial in Reconstruction-Era Public Discourse." Journal of Southern History 77, No. 1 (February 2011), 53--90.

Pilgrim, David. "The Coon Caricature." Ferris State University: Michigan College Campuses in Big Rapids MI, Grand Rapids MI, Off Campus Locations Across Michigan. October 2000. https://www.ferris.edu/jimcrow/coon/

Richardson, Riché. Black Masculinity and the U.S. South: From Uncle Tom to Gangsta. Athens: University of Georgia Press, 2007.

Richardson, Sarah. "As American as Jim Crow." American History 53, no. 1 (April 2018), 52--59.

Urwand, Ben. "The Black Image on the White Screen: Representations of African Americans from the Origins of Cinema to The Birth of a Nation." Journal of American Studies, 52 (2018), 1, 45-64.

Wingo, Rebecca S. "The 'Forgotten Era': Race and Gender in Ann Stephens's Dime Novel Frontier." Frontiers: A Journal of Women Studies. Vol. 38 Issue 3 (2017), 121-140.

Young, Iris Marion. "The Logic of Masculinist Protection: Reflections on the Current Security State." Signs, Vol. 29, No. 1 (Autumn 2003), 1-25.
