project:
  type: website

website:
  title: Testing
  navbar:
    background: primary
    left:
      - text: "Home"
        file: index.qmd
      - text: "Subsection"
        file: subsection/index.qmd
      - about.qmd

  sidebar:
    - title: "Subsection"
      style: "docked"
      background: light
      contents:
        - subsection/index.qmd
        - subsection/thing1.qmd

    - title: "Placeholder thing"

format:
  html:
    theme: cosmo
