---
title: "4: Balance and Sequentiality in Bayesian Analyses"
editor_options: 
  chunk_output_type: console
---

```{r load-packages, warning=FALSE, message=FALSE}

# Load packages that will be used in this chapter
library(bayesrules)
library(tidyverse)
library(janitor)

```

# 4.1 Different priors, different posteriors

```{r}
# Import data
data(bechdel, package = "bayesrules")

# Take a sample of 20 movies
set.seed(84735)
bechdel_20 <- bechdel %>% 
  sample_n(20)

bechdel_20 %>% 
  head(3)

bechdel_20 %>% 
  tabyl(binary) %>% 
  adorn_totals("row")

```

```{r}

bechdel %>% 
  filter(year == 1991) %>% 
  tabyl(binary) %>% 
  adorn_totals("row")

bechdel %>% 
  filter(year == 2000) %>% 
  tabyl(binary) %>% 
  adorn_totals("row")

bechdel %>% 
  filter(year == 2013) %>% 
  tabyl(binary) %>% 
  adorn_totals("row")

```



# 4.2 Different data, different posteriors


```{r}

plot_beta(alpha = 10, beta = 10)

# Plot the Beta-Binomial model
plot_beta_binomial(alpha = 10, beta = 10, y = 15, n = 47)

# Obtain numerical summaries of the Beta-Binomial model
summarize_beta_binomial(alpha = 10, beta = 10, y = 15, n = 47)

```

