<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jamie Esmond">
<meta name="dcterms.date" content="2023-01-27">

<title>Problem Set 2: Regression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="Jamie-Esmond_Problem-Set-2_files/libs/clipboard/clipboard.min.js"></script>
<script src="Jamie-Esmond_Problem-Set-2_files/libs/quarto-html/quarto.js"></script>
<script src="Jamie-Esmond_Problem-Set-2_files/libs/quarto-html/popper.min.js"></script>
<script src="Jamie-Esmond_Problem-Set-2_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Jamie-Esmond_Problem-Set-2_files/libs/quarto-html/anchor.min.js"></script>
<link href="Jamie-Esmond_Problem-Set-2_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Jamie-Esmond_Problem-Set-2_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Jamie-Esmond_Problem-Set-2_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Jamie-Esmond_Problem-Set-2_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Jamie-Esmond_Problem-Set-2_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

<script src="Jamie-Esmond_Problem-Set-2_files/libs/kePrint-0.0.1/kePrint.js"></script>
<link href="Jamie-Esmond_Problem-Set-2_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Problem Set 2: Regression</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Jamie Esmond </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 27, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(modelsummary)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Load penguins data</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>penguins <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/penguins.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="task-1-penguins" class="level1">
<h1>Task 1: Penguins</h1>
<p>Between 2007 and 2009, researchers collected data on penguins in three islands in the Palmer Archipelago in Antarctica: Biscoe, Dream, and Torgersen. The <code>penguins</code> dataset has data for 342 penguins from 3 different species: Chinstrap, Gentoo, and AdÃ©lie. It includes the following variables:</p>
<ul>
<li><code>species</code>: The penguin’s species (Chinstrap, Gentoo, and AdÃ©lie)</li>
<li><code>island</code>: The island where the penguin lives (Biscoe, Dream, and Torgersen)</li>
<li><code>bill_length_mm</code>: The length of the penguin’s bill, in millimeters (distance from the penguin’s face to the tip of the bill)</li>
<li><code>bill_depth_mm</code>: The depth of the penguin’s bill, in millimeters (height of the bill; distance from the bottom of the bill to the top of the bill)</li>
<li><code>flipper_length_mm</code>: The length of the penguin’s flippers, in millimeters</li>
<li><code>body_mass_g</code>: The weight of the penguin, in grams</li>
<li><code>sex</code>: The sex of the penguin</li>
<li><code>year</code>: The year the observation was made</li>
</ul>
<section id="exploratory-analysis" class="level2">
<h2 class="anchored" data-anchor-id="exploratory-analysis">Exploratory analysis</h2>
<p>What is the relationship between penguin weight and bill depth? This plot shows some initial trends:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> penguins, </span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> bill_depth_mm, <span class="at">y =</span> body_mass_g)) <span class="sc">+</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Bill Depth (mm)"</span>, </span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Body Mass (g)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Jamie-Esmond_Problem-Set-2_files/figure-html/plot-penguin-weight-depth-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>This plot shows that, generally, as bill depth grows, body mass increases assuming whatever is causing the two separate clusters to appear, which is unclear from this plot, is controlled for. These clusters indicate that there may be other factors influencing the body mass of penguins.</strong></p>
<p>Make a new plot that colors these points by species. What can you tell about the relationship between bill depth and penguin weight?</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> penguins, </span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> bill_depth_mm, <span class="at">y =</span> body_mass_g)) <span class="sc">+</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">color =</span> species)) <span class="sc">+</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Bill Depth (mm)"</span>, </span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Body Mass (g)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Jamie-Esmond_Problem-Set-2_files/figure-html/plot-penguin-weight-depth-by-species-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>This plot clearly shows that Gentoo penguins have smaller bill depth than Adelie and Chinstrap penguins, but within there own species, bill depth still has a positive correlation to body mass. Though the Adelie and Chinstrap penguins are generally smaller in body mass and bill depth than Gentoo penguins, within their species, there is still a postive correlation between bill depth and body mass.</strong></p>
<p>Add a <code>geom_smooth()</code> layer to the plot and make sure it uses a straight line (hint: include <code>method="lm"</code> in the function). What does this tell you about the relationship between bill depth and body mass?</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> penguins, </span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> bill_depth_mm, <span class="at">y =</span> body_mass_g, <span class="at">color =</span> species)) <span class="sc">+</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>) <span class="sc">+</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Bill Depth (mm)"</span>, </span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Body Mass (g)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Jamie-Esmond_Problem-Set-2_files/figure-html/plot-penguin-weight-depth-by-species-with-lines-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>As stated earlier, this plot shows even more clearly the upward slope of the trendline, indicating a positive relationship between bill depth and body mass.</strong></p>
<p>Change the plot so that there’s a single line for all the points instead of one line per species. How does the slope of this single line differ from the slopes of the species specific lines? <strong><em>Why??</em></strong></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> penguins, </span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> bill_depth_mm, <span class="at">y =</span> body_mass_g)) <span class="sc">+</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>) <span class="sc">+</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Bill Depth (mm)"</span>, </span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Body Mass (g)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Jamie-Esmond_Problem-Set-2_files/figure-html/plot-penguin-weight-depth-by-species-with-one-line-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>When species is not controlled for, the there is an overall downward slope, indicating a negative relationship between bill depth and body mass. This is because there are more penguins in the sample from either Adelie or Chinstrap species than from the Gentoo species. Since the bill depth is higher for the first two species, but those species also generally have a smaller body mass, it weights the distribution in a misleading way. </strong></p>
<p>What is the relationship between flipper length and body mass? Make another plot with <code>flipper_length_mm</code> on the x-axis, <code>body_mass_g</code> on the y-axis, and points colored by <code>species</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> penguins, </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> flipper_length_mm, <span class="at">y =</span> body_mass_g, <span class="at">color =</span> species)) <span class="sc">+</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>) <span class="sc">+</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Flipper Length (mm)"</span>, </span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Body Mass (g)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Jamie-Esmond_Problem-Set-2_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>This plot shows that there is a positive relationship between flipper length and body mass. </strong></p>
<p>Facet the plot by island (<code>island</code>)</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> penguins,</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> flipper_length_mm, <span class="at">y =</span> body_mass_g, <span class="at">color =</span> species)) <span class="sc">+</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="fu">vars</span>(island)) <span class="sc">+</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Flipper Length (mm)"</span>, </span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Body Mass (g)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Jamie-Esmond_Problem-Set-2_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Tell a story about the relationship between flipper length and weight in these three penguin species.</p>
<p><strong>As flipper length increases, body mass also increases. Though the Gentoo penguins seem to be larger in general, both in flipper length and body mass, the trend is consistent among all species that with longer flippers there is a higher body mass.</strong></p>
<p>Tell a story about the distribution of penguins across the three islands.</p>
<p><strong>Adelie penguins are found on all three islands, but Gentoo penguins and Chinstrap penguins are only found on Biscoe and Dream, respectively. Biscoe island contains both Adelie and Gentoo penguins. Dream island contains both Adelie and Chinstrap penguins. Torgersen island contains only Adelie penguins. If the species were not coded by color in these plots, one might conclude that penguins are larger on the island of Biscoe because the overall average body mass of penguins on that island is larger. The colors help convey that the difference in size is probably better explained by the species of penguin than the location.</strong></p>
</section>
<section id="models" class="level2">
<h2 class="anchored" data-anchor-id="models">Models</h2>
<section id="predicting-weight-with-bill-depth" class="level3">
<h3 class="anchored" data-anchor-id="predicting-weight-with-bill-depth">Predicting weight with bill depth</h3>
<p>Does bill depth predict penguin weight?</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>model_depth_weight <span class="ot">&lt;-</span> <span class="fu">lm</span>(body_mass_g <span class="sc">~</span> bill_depth_mm,</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>                         <span class="at">data =</span> penguins)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(model_depth_weight, <span class="at">conf.int =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 7
  term          estimate std.error statistic  p.value conf.low conf.high
  &lt;chr&gt;            &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)      7489.     335.      22.3  1.13e-68    6829.     8148.
2 bill_depth_mm    -192.      19.4     -9.87 2.28e-20    -230.     -153.</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(model_depth_weight)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 12
  r.squared adj.r.squa…¹ sigma stati…²  p.value    df logLik   AIC   BIC devia…³
      &lt;dbl&gt;        &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;
1     0.223        0.220  708.    97.4 2.28e-20     1 -2729. 5463. 5475.  1.70e8
# … with 2 more variables: df.residual &lt;int&gt;, nobs &lt;int&gt;, and abbreviated
#   variable names ¹​adj.r.squared, ²​statistic, ³​deviance</code></pre>
</div>
</div>
<p>What happens as bills get taller? Is the association statistically significant? How confident are you about these results? (Hint: look at the <span class="math inline">\(R^2\)</span>)</p>
<p><strong>The intercept is 7488.65, which means that the average penguin will have a body mass of 7488.65 grams when the bill depth is 0 mm. This does not mean much since no penguin has a bill depth of 0 mm. The slope of <code>bill_depth_mm</code> is -191.64, which means that a 1 mm increase in bill depth is associated with a 191.64 gram decrease in body mass, on average, without controlling for any other factors. The association is statistically significant because the p value is virtually zero. The <span class="math inline">\(R^2\)</span> here is 0.223, which means that bill depth explains only 22.3% of the variation in penguin body mass. </strong></p>
</section>
<section id="predicting-weight-with-bill-depth-and-flipper-length" class="level3">
<h3 class="anchored" data-anchor-id="predicting-weight-with-bill-depth-and-flipper-length">Predicting weight with bill depth and flipper length</h3>
<p>RUN A MODEL that predicts weight with bill depth and flipper length (i.e.&nbsp;body_mass_g ~ bill_depth_mm + flipper_length_mm)</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>model_weight_depth_flipper <span class="ot">&lt;-</span> <span class="fu">lm</span>(body_mass_g <span class="sc">~</span> </span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>                                   bill_depth_mm <span class="sc">+</span> </span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>                                   flipper_length_mm,</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>                         <span class="at">data =</span> penguins)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(model_weight_depth_flipper, <span class="at">conf.int =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 7
  term              estimate std.error statistic  p.value conf.low conf.high
  &lt;chr&gt;                &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)        -6542.     541.      -12.1  2.99e-28 -7606.     -5478. 
2 bill_depth_mm         22.6     13.3       1.70 8.92e- 2    -3.49      48.8
3 flipper_length_mm     51.5      1.87     27.6  7.72e-89    47.9       55.2</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(model_weight_depth_flipper)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 12
  r.squared adj.r.squ…¹ sigma stati…²   p.value    df logLik   AIC   BIC devia…³
      &lt;dbl&gt;       &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;
1     0.761       0.760  393.    540. 4.23e-106     2 -2527. 5062. 5077.  5.24e7
# … with 2 more variables: df.residual &lt;int&gt;, nobs &lt;int&gt;, and abbreviated
#   variable names ¹​adj.r.squared, ²​statistic, ³​deviance</code></pre>
</div>
</div>
<p>Did the size of the bill depth coefficient change after controlling for flipper length?</p>
<p><strong>The intercept is -6541.91, which means that the average penguin will have a body mass of -6541.91 grams when the bill depth and the flipper length is 0 mm. This does not mean much since a penguin cannot have a negative weight, and no penguin has a bill depth or flipper length of 0 mm. The slope of <code>bill_depth_mm</code> is now 22.63, which means that a 1 mm increase in bill depth is associated with a 22.63 gram increase in body mass, on average, when flipper length is held constant. The slope of <code>flipper_length_mm</code> is 51.54, which means that a 1 mm increase in flipper length is associated with a 51.54 gram increase in body mass, on average, when bill depth is held constant. The coefficient for <code>bill_depth_mm</code> completely changed directions, now indicating a positive association between the two variables. The association is still statistically significant because the p value is still virtually zero, even though the correlation is now in a different direction. The adjusted <span class="math inline">\(R^2\)</span> here is 0.76, which means that bill depth and flipper length explain 76% of the variation in penguin body mass.</strong></p>
</section>
<section id="predicting-weight-with-bill-depth-flipper-length-and-species" class="level3">
<h3 class="anchored" data-anchor-id="predicting-weight-with-bill-depth-flipper-length-and-species">Predicting weight with bill depth, flipper length, and species</h3>
<p>RUN A MODEL that predicts weight with bill depth, flipper length, and species.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>model_weight_depth_flipper_species <span class="ot">&lt;-</span> <span class="fu">lm</span>(body_mass_g <span class="sc">~</span> </span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>                                          bill_depth_mm <span class="sc">+</span> </span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>                                          flipper_length_mm <span class="sc">+</span> </span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>                                          species,</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>                                          <span class="at">data =</span> penguins)</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(model_weight_depth_flipper_species, <span class="at">conf.int =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 7
  term              estimate std.error statistic  p.value conf.low conf.high
  &lt;chr&gt;                &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)        -4527.     517.       -8.76 9.87e-17  -5544.    -3510. 
2 bill_depth_mm        182.      18.4       9.93 1.45e-20    146.      218. 
3 flipper_length_mm     25.7      3.10      8.30 2.63e-15     19.6      31.8
4 speciesChinstrap    -132.      51.4      -2.57 1.07e- 2   -233.      -30.9
5 speciesGentoo       1289.     133.        9.71 8.28e-20   1028.     1550. </code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(model_weight_depth_flipper_species)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 12
  r.squared adj.r.squ…¹ sigma stati…²   p.value    df logLik   AIC   BIC devia…³
      &lt;dbl&gt;       &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;
1     0.832       0.830  331.    417. 4.66e-129     4 -2467. 4946. 4969.  3.69e7
# … with 2 more variables: df.residual &lt;int&gt;, nobs &lt;int&gt;, and abbreviated
#   variable names ¹​adj.r.squared, ²​statistic, ³​deviance</code></pre>
</div>
</div>
<p>What do the species coefficients mean? Did the bill depth coefficient change after controlling for both flipper length and species?</p>
<p><strong>The intercept is -4526.89, which means that the average penguin will have a body mass of -4526.89 grams when the bill depth and the flipper length is 0 mm and the species is Adelie (the reference group). This does not mean much since a penguin cannot have a negative weight, and no penguin has a bill depth or flipper length of 0 mm. The slope of <code>bill_depth_mm</code> is now 182.36, which means that a 1 mm increase in bill depth is associated with a 182.36 gram increase in body mass, on average, when flipper length and species are held constant. The slope of <code>flipper_length_mm</code> is now 25.7, which means that a 1 mm increase in flipper length is associated with a 25.7 gram increase in body mass, on average, when bill depth and species are held constant. The coefficient for <code>bill_depth_mm</code> became even higher, indicating an even stronger positive association between the two variables, hold the other constant. The coefficient for Chinstrap is -131.97, which means that controlling for bill depth and flipper length, Chinstrap penguins are 131.97 grams lighter than Adelie penguins. The coefficient for Gentoo is 1288.97, which means that controlling for bill depth and flipper length, Gentoo penguins are 1288.97 grams heavier than Adelie penguins. The association for all variables is statistically significant because the p values are all virtually zero. The adjusted <span class="math inline">\(R^2\)</span> here is 0.83, which means that bill depth, flipper length, and species explain 83% of the variation in penguin body mass.</strong></p>
</section>
</section>
<section id="all-models-at-the-same-time" class="level2">
<h2 class="anchored" data-anchor-id="all-models-at-the-same-time">All models at the same time</h2>
<div class="cell">

<style type="text/css">
.table caption {
  text-align: center;
  font-weight: bold;
  font-size: 150%;
  color: #000;
}
</style>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Right now there's only one model here. Add the others from above (whatever you</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="co"># called them) like so: </span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="co"># modelsummary(list(model_depth_weight, some_other_model, yet_another_model, etc))</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>notes <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"t statistics in parentheses</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>           <span class="st">"+ p &lt; 0.1, * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001"</span>)</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a><span class="fu">modelsummary</span>(<span class="fu">list</span>(<span class="st">"Model 1"</span><span class="ot">=</span>model_depth_weight, </span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>                  <span class="st">"Model 2"</span><span class="ot">=</span>model_weight_depth_flipper, </span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>                  <span class="st">"Model 3"</span><span class="ot">=</span>model_weight_depth_flipper_species),</span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>             <span class="at">coef_rename =</span> <span class="fu">c</span>(<span class="at">bill_depth_mm =</span> <span class="st">"Bill Depth (mm)"</span>, </span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>                             <span class="at">flipper_length_mm =</span> <span class="st">"Flipper Length (mm)"</span>, </span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>                             <span class="at">speciesChinstrap =</span> <span class="st">"Chinstrap"</span>, </span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>                             <span class="at">speciesGentoo =</span> <span class="st">"Gentoo"</span>),</span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a>             <span class="at">output =</span> <span class="st">"kableExtra"</span>,</span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a>             <span class="at">estimate =</span> <span class="st">"{estimate} {stars}"</span>,</span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a>             <span class="at">statistic =</span> <span class="st">"statistic"</span>,</span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a>             <span class="at">title =</span> <span class="st">"Penguin Models"</span>,</span>
<span id="cb23-20"><a href="#cb23-20" aria-hidden="true" tabindex="-1"></a>             <span class="at">fmt =</span>  <span class="dv">2</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb23-21"><a href="#cb23-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">row_spec</span>(<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>,<span class="dv">5</span>,<span class="dv">7</span>,<span class="dv">9</span>), <span class="at">background =</span> <span class="st">"#92c0fc"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb23-22"><a href="#cb23-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">footnote</span>(<span class="at">general =</span> notes, <span class="at">footnote_as_chunk =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;border-bottom: 0;">
<caption>Penguin Models</caption>
 <thead>
  <tr>
   <th style="text-align:left;">   </th>
   <th style="text-align:center;"> Model 1 </th>
   <th style="text-align:center;"> &nbsp;Model 2 </th>
   <th style="text-align:center;"> &nbsp;Model 3 </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;background-color: #92c0fc !important;"> (Intercept) </td>
   <td style="text-align:center;background-color: #92c0fc !important;"> 7488.65 *** </td>
   <td style="text-align:center;background-color: #92c0fc !important;"> −6541.91 *** </td>
   <td style="text-align:center;background-color: #92c0fc !important;"> −4526.89 *** </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:center;"> (22.34) </td>
   <td style="text-align:center;"> (−12.10) </td>
   <td style="text-align:center;"> (−8.76) </td>
  </tr>
  <tr>
   <td style="text-align:left;background-color: #92c0fc !important;"> Bill Depth (mm) </td>
   <td style="text-align:center;background-color: #92c0fc !important;"> −191.64 *** </td>
   <td style="text-align:center;background-color: #92c0fc !important;"> 22.63 + </td>
   <td style="text-align:center;background-color: #92c0fc !important;"> 182.36 *** </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:center;"> (−9.87) </td>
   <td style="text-align:center;"> (1.70) </td>
   <td style="text-align:center;"> (9.93) </td>
  </tr>
  <tr>
   <td style="text-align:left;background-color: #92c0fc !important;"> Flipper Length (mm) </td>
   <td style="text-align:center;background-color: #92c0fc !important;">  </td>
   <td style="text-align:center;background-color: #92c0fc !important;"> 51.54 *** </td>
   <td style="text-align:center;background-color: #92c0fc !important;"> 25.70 *** </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> (27.64) </td>
   <td style="text-align:center;"> (8.30) </td>
  </tr>
  <tr>
   <td style="text-align:left;background-color: #92c0fc !important;"> Chinstrap </td>
   <td style="text-align:center;background-color: #92c0fc !important;">  </td>
   <td style="text-align:center;background-color: #92c0fc !important;">  </td>
   <td style="text-align:center;background-color: #92c0fc !important;"> −131.97 * </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> (−2.57) </td>
  </tr>
  <tr>
   <td style="text-align:left;background-color: #92c0fc !important;"> Gentoo </td>
   <td style="text-align:center;background-color: #92c0fc !important;">  </td>
   <td style="text-align:center;background-color: #92c0fc !important;">  </td>
   <td style="text-align:center;background-color: #92c0fc !important;"> 1288.97 *** </td>
  </tr>
  <tr>
   <td style="text-align:left;box-shadow: 0px 1px">  </td>
   <td style="text-align:center;box-shadow: 0px 1px">  </td>
   <td style="text-align:center;box-shadow: 0px 1px">  </td>
   <td style="text-align:center;box-shadow: 0px 1px"> (9.71) </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Num.Obs. </td>
   <td style="text-align:center;"> 342 </td>
   <td style="text-align:center;"> 342 </td>
   <td style="text-align:center;"> 342 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> R2 </td>
   <td style="text-align:center;"> 0.223 </td>
   <td style="text-align:center;"> 0.761 </td>
   <td style="text-align:center;"> 0.832 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> R2 Adj. </td>
   <td style="text-align:center;"> 0.220 </td>
   <td style="text-align:center;"> 0.760 </td>
   <td style="text-align:center;"> 0.830 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> AIC </td>
   <td style="text-align:center;"> 5463.3 </td>
   <td style="text-align:center;"> 5061.9 </td>
   <td style="text-align:center;"> 4945.7 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BIC </td>
   <td style="text-align:center;"> 5474.8 </td>
   <td style="text-align:center;"> 5077.3 </td>
   <td style="text-align:center;"> 4968.7 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Log.Lik. </td>
   <td style="text-align:center;"> −2728.667 </td>
   <td style="text-align:center;"> −2526.968 </td>
   <td style="text-align:center;"> −2466.846 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> RMSE </td>
   <td style="text-align:center;"> 706.00 </td>
   <td style="text-align:center;"> 391.45 </td>
   <td style="text-align:center;"> 328.34 </td>
  </tr>
</tbody>
<tfoot><tr><td style="padding: 0; " colspan="100%">
<span style="font-style: italic;">Note: </span> <sup></sup> t statistics in parentheses<br> <sup></sup> + p &lt; 0.1, * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001</td></tr></tfoot>
</table>

</div>
</div>
<hr>
</section>
</section>
<section id="task-2-food-access-and-mortality" class="level1">
<h1>Task 2: Food access and mortality</h1>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Make sure you look at this dataset by clicking on its name in the Environment</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="co"># panel in RStudio. Sort some of the different columns and look around to get a</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="co"># feel for what's in the data</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>food_health <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/food_health_politics.csv"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 3143 Columns: 26
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (2): state, county
dbl (24): FIPS, low_access_pop, low_access_change, pct_low_access_pop, child...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
<p>We’re interested in looking at the relationships between food access, mortality, and politics. Do do this, we look at data from three different sources:</p>
<ul>
<li>The USDA’s <a href="https://www.ers.usda.gov/data-products/food-environment-atlas/documentation/">Food Environment Atlas</a></li>
<li>The CDC’s <a href="http://wonder.cdc.gov/cmf-icd10.html">“Compressed Mortality File 1999-2015 Series 20 No.&nbsp;2U, 2016”</a></li>
<li>2016 election results (found all over the internet)</li>
</ul>
<p>Each row in the dataset is a US county. The main outcome we care about is <code>mortality_rate</code>, or the number of deaths per 100,000 people in a county between 2013-2015. Other interesting variables in the dataset include:</p>
<ul>
<li><code>pct_low_access_pop</code>: Percent of the county’s population with low access to food</li>
<li><code>pct_children_low_access</code>: Percent of the county’s children with low access to food</li>
<li><code>grocery_stores_per_1000</code>: Number of grocery stores in a county (per 1,000 residents)</li>
<li><code>snap_stores_per_1000</code>: Number of stores that accept SNAP (food stamps) in a county (per 1,000 residents)</li>
<li><code>fastfood_per_1000</code>: Number of fast food stores in a county (per 1,000 residents)</li>
<li><code>per_dem_2012</code>: Percent of the county that voted for Obama in 2012</li>
<li><code>per_dem_2016</code>: Percent of the county that voted for Clinton in 2016</li>
</ul>
<section id="exploratory-analysis-1" class="level2">
<h2 class="anchored" data-anchor-id="exploratory-analysis-1">Exploratory analysis</h2>
<section id="how-related-are-mortality-rate-and-access-to-food" class="level3">
<h3 class="anchored" data-anchor-id="how-related-are-mortality-rate-and-access-to-food">How related are mortality rate and access to food?</h3>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Notice how this is a little different from what was in the complete example</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="co"># with SAT scores. It's not possible to calculate correlations when there is</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="co"># missing data. The `use = "complete.obs"` argument here tells R to ignore any</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="co"># rows where either mortality_rate or pct_low_access_pop is missing</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(food_health<span class="sc">$</span>mortality_rate, food_health<span class="sc">$</span>pct_low_access_pop,</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">use =</span> <span class="st">"complete.obs"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.1631545</code></pre>
</div>
</div>
<p>This is backwards from what you might expect, since it trends downward (i.e.&nbsp;the mortality rate is lower in counties with a greater proportion of the population with low access to food). Why might that be? Is there really a relationship?</p>
<p><strong>This plot does have a downward slope, but it is not very steep. There could be other factors that are not displayed in this plot that could be impacting mortality rates. For example, rural counties may have less access to food because the population is lower and residents are more likely to live further away from grocery stores. It is unclear what the metric for “low access to food” is here.</strong></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Use warning=FALSE in the chunk options to remove the warning about missing data</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(food_health, <span class="fu">aes</span>(<span class="at">x =</span> pct_low_access_pop, <span class="at">y =</span> mortality_rate)) <span class="sc">+</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>) <span class="sc">+</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"% of county with low access to food"</span>, </span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Mortality rate (per 100,000 residents)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Jamie-Esmond_Problem-Set-2_files/figure-html/plot-mortality-food-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="how-related-are-mortality-rate-and-the-prevalence-of-fast-food-restaurants" class="level3">
<h3 class="anchored" data-anchor-id="how-related-are-mortality-rate-and-the-prevalence-of-fast-food-restaurants">How related are mortality rate and the prevalence of fast food restaurants?</h3>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>model_fastfood <span class="ot">&lt;-</span> <span class="fu">lm</span>(mortality_rate <span class="sc">~</span> fastfood_per_1000,</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>                         <span class="at">data =</span> food_health)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(model_fastfood, <span class="at">conf.int =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 7
  term              estimate std.error statistic p.value conf.low conf.high
  &lt;chr&gt;                &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)          829.       5.67    146.    0         818.     840.  
2 fastfood_per_1000    -21.3      8.68     -2.45  0.0142    -38.3     -4.28</code></pre>
</div>
</div>
<p><strong>The mortality rate and the prevalence of fast food restaurants are related according to this data. For every increase in fast food restaurants per 1000 residents by one, the mortality rate drops by 21.29 per 100,000 residents. The p value is less than .05, meaning the relationship is statistically significant. This is surprising because one would expect an increase in the prevalence of fast food restaurants would increase the mortality rate in the area. However, according to this plot, most places have less than 2 fast food restaurants per 1000 residents; there are only a few areas with more than 2, and even less with more than 4. These outliers may be skewing the results. </strong></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(food_health, <span class="fu">aes</span>(<span class="at">x =</span> fastfood_per_1000, <span class="at">y =</span> mortality_rate)) <span class="sc">+</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>) <span class="sc">+</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Fast food per 1000 residents"</span>, </span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Mortality rate (per 100,000 residents)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Jamie-Esmond_Problem-Set-2_files/figure-html/plot-mortality-fastfood-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="how-related-are-mortality-rate-and-the-prevalence-of-snap-stores-per-1000-residents" class="level3">
<h3 class="anchored" data-anchor-id="how-related-are-mortality-rate-and-the-prevalence-of-snap-stores-per-1000-residents">How related are mortality rate and the prevalence of SNAP stores per 1,000 residents?</h3>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>model_snap <span class="ot">&lt;-</span> <span class="fu">lm</span>(mortality_rate <span class="sc">~</span> snap_stores_per_1000,</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>                         <span class="at">data =</span> food_health)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(model_snap, <span class="at">conf.int =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 7
  term                 estimate std.error statistic   p.value conf.low conf.high
  &lt;chr&gt;                   &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)              654.      6.35     103.  0             642.      667.
2 snap_stores_per_1000     174.      6.30      27.7 3.22e-151     162.      187.</code></pre>
</div>
</div>
<p><strong>The mortality rate and the prevalence of SNAP stores are related according to this data. For every increase in SNAP stores per 1000 residents by one, the mortality rate increases by 174.49 per 100,000 residents. The p value is virtually zero, meaning the relationship is very statistically significant. This unsurprising because one would expect an increase in the prevalence of SNAP stores would increase the mortality rate in the area by providing access to food to more residents. </strong></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(food_health, <span class="fu">aes</span>(<span class="at">x =</span> snap_stores_per_1000, <span class="at">y =</span> mortality_rate)) <span class="sc">+</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>) <span class="sc">+</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"SNAP stores per 1000 residents"</span>, </span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Mortality rate (per 100,000 residents)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Jamie-Esmond_Problem-Set-2_files/figure-html/plot-mortality-snap-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="how-related-are-mortality-rate-and-the-percent-of-the-county-that-voted-for-democrats-in-2016" class="level3">
<h3 class="anchored" data-anchor-id="how-related-are-mortality-rate-and-the-percent-of-the-county-that-voted-for-democrats-in-2016">How related are mortality rate and the percent of the county that voted for Democrats in 2016?</h3>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>model_vote <span class="ot">&lt;-</span> <span class="fu">lm</span>(mortality_rate <span class="sc">~</span> per_dem_2016,</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>                         <span class="at">data =</span> food_health)</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(model_vote, <span class="at">conf.int =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 7
  term         estimate std.error statistic  p.value conf.low conf.high
  &lt;chr&gt;           &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)      861.      6.05    142.   0            849.      873.
2 per_dem_2016    -139.     17.2      -8.13 6.36e-16    -173.     -106.</code></pre>
</div>
</div>
<p><strong>The mortality rate and the percent of the county that voted for Democrats in 2016 are related according to this data. For every one point increase in the percent of the county that voted for Democrats in 2016 per 1000 residents, the mortality rate decreased by 139.35 per 100,000 residents. The p value is virtually zero, meaning the relationship is very statistically significant. </strong></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(food_health, <span class="fu">aes</span>(<span class="at">x =</span> per_dem_2016<span class="sc">*</span><span class="dv">100</span>, <span class="at">y =</span> mortality_rate)) <span class="sc">+</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>) <span class="sc">+</span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Percent of Vote for Democrats"</span>, </span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Mortality rate (per 100,000 residents)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Jamie-Esmond_Problem-Set-2_files/figure-html/plot-mortality-2016-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="models-1" class="level2">
<h2 class="anchored" data-anchor-id="models-1">Models</h2>
<section id="does-access-to-food-predict-mortality" class="level3">
<h3 class="anchored" data-anchor-id="does-access-to-food-predict-mortality">Does access to food predict mortality?</h3>
<p><strong>According to this model, there is a negative relationship between food access and mortality. When low access to food increases, the mortality rate decreases.</strong></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>model_mortality_food <span class="ot">&lt;-</span> <span class="fu">lm</span>(mortality_rate <span class="sc">~</span> pct_low_access_pop,</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>                           <span class="at">data =</span> food_health)</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(model_mortality_food, <span class="at">conf.int =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 7
  term               estimate std.error statistic  p.value conf.low conf.high
  &lt;chr&gt;                 &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)            845.      4.06    208.   0            837.     853. 
2 pct_low_access_pop    -125.     13.5      -9.23 4.94e-20    -151.     -98.1</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(model_mortality_food)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 12
  r.squared adj.r.s…¹ sigma stati…²  p.value    df  logLik    AIC    BIC devia…³
      &lt;dbl&gt;     &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;
1    0.0266    0.0263  146.    85.2 4.94e-20     1 -19948. 39901. 39920.  6.63e7
# … with 2 more variables: df.residual &lt;int&gt;, nobs &lt;int&gt;, and abbreviated
#   variable names ¹​adj.r.squared, ²​statistic, ³​deviance</code></pre>
</div>
</div>
<p>What happens as the percent of low access to food goes up by 1%? Is that significant? Again, this is backwards from what you’d expect—as the percent of low access goes up, mortality drops. Why might that be? How much do you trust this finding? (Hint: look at the <span class="math inline">\(R^2\)</span> value)</p>
<p><strong>As the percent of residents with low food access increases by one point, the mortality rate decreases by 845.31 (per 100,000 residents). This relationship is statistically significant because the p value is virtually zero. There could be other factors that are not displayed in this data that could be impacting mortality rates. For example, rural counties may have less access to food because the population is lower and residents are more likely to live further away from grocery stores. It is unclear what the metric for “low access to food” is here. According to the <span class="math inline">\(R^2\)</span> value, low food access only accounts for 26.6% of the variation in mortality rate.</strong></p>
</section>
<section id="do-more-snap-stores-per-person-predict-mortality" class="level3">
<h3 class="anchored" data-anchor-id="do-more-snap-stores-per-person-predict-mortality">Do more SNAP stores per person predict mortality?</h3>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>model_mortality_snap <span class="ot">&lt;-</span> <span class="fu">lm</span>(mortality_rate <span class="sc">~</span> snap_stores_per_1000,</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>                           <span class="at">data =</span> food_health)</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(model_mortality_snap, <span class="at">conf.int =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 7
  term                 estimate std.error statistic   p.value conf.low conf.high
  &lt;chr&gt;                   &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)              654.      6.35     103.  0             642.      667.
2 snap_stores_per_1000     174.      6.30      27.7 3.22e-151     162.      187.</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(model_mortality_snap)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 12
  r.squared adj.r.…¹ sigma stati…²   p.value    df  logLik    AIC    BIC devia…³
      &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;
1     0.198    0.198  131.    768. 3.22e-151     1 -19595. 39196. 39214.  5.37e7
# … with 2 more variables: df.residual &lt;int&gt;, nobs &lt;int&gt;, and abbreviated
#   variable names ¹​adj.r.squared, ²​statistic, ³​deviance</code></pre>
</div>
</div>
<p>What happens as the proportion of SNAP stores goes up? Do you trust this number more or less than low access to food?</p>
<p><strong>As the number of SNAP stores per 1000 residents increases by one, the mortality rate increases by 174.49 (per 100,000 residents). This relationship is statistically significant because the p value is virtually zero. According to the <span class="math inline">\(R^2\)</span> value, low food access only accounts for 19.8% of the variation in mortality rate, which is even less than what low food access accounted for. Again, there are likely other factors such as neighborhood characteristics and income that might better explain this surprising result. For example, stores that accept SNAP are more likely to be located in low income neighborhoods; people in low income neighborhoods are more likely to be low income, and less income decreases access to medical care, which, of course, can increase mortality.</strong></p>
</section>
<section id="do-election-results-and-access-to-food-and-snap-stores-predict-mortality" class="level3">
<h3 class="anchored" data-anchor-id="do-election-results-and-access-to-food-and-snap-stores-predict-mortality">Do election results and access to food and SNAP stores predict mortality?</h3>
<p>RUN A MODEL THAT PREDICTS MORTALITY WITH A BUNCH OF COVARIATES (i.e.&nbsp;mortality_rate ~ pct_low_access_pop + snap_stores_per_1000 + per_dem_2016 + anything else you want to throw in)</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>model_mortality_many <span class="ot">&lt;-</span> <span class="fu">lm</span>(mortality_rate <span class="sc">~</span> pct_low_access_pop <span class="sc">+</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>                                            snap_stores_per_1000 <span class="sc">+</span></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>                                            fastfood_per_1000 <span class="sc">+</span></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>                                            per_dem_2016,</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>                           <span class="at">data =</span> food_health)</span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(model_mortality_many, <span class="at">conf.int =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 7
  term                 estimate std.error statistic   p.value conf.low conf.high
  &lt;chr&gt;                   &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)             744.       8.92     83.4  0            726.     761.  
2 pct_low_access_pop     -170.      12.3     -13.9  1.41e- 42   -194.    -146.  
3 snap_stores_per_1000    181.       6.06     29.9  5.60e-173    169.     193.  
4 fastfood_per_1000       -17.6      7.68     -2.29 2.19e-  2    -32.7     -2.55
5 per_dem_2016           -149.      15.2      -9.82 1.92e- 22   -179.    -119.  </code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(model_mortality_many)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 12
  r.squared adj.r.…¹ sigma stati…²   p.value    df  logLik    AIC    BIC devia…³
      &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;
1     0.266    0.265  125.    279. 3.38e-205     4 -19331. 38674. 38710.  4.86e7
# … with 2 more variables: df.residual &lt;int&gt;, nobs &lt;int&gt;, and abbreviated
#   variable names ¹​adj.r.squared, ²​statistic, ³​deviance</code></pre>
</div>
</div>
<p>Interpret the different coefficients. How predictive is this model (i.e.&nbsp;what’s the R2)? Do you believe this model?</p>
<p><strong>When controlling for low access to food, the number of SNAP stores per 1000 residents, and the prevalence of fast food restaurants, as the percent of the county who voted Democrat in 2016 increases by one point, the mortality rate decreases by 149.2 (per 100,000 residents). As the percent of residents with low access to food increases, the mortality rate decreases when holding all other variables constant. The prevalence of SNAP stores has a positive relationship with the mortality rate, but the prevalence of fast food restaurants’ relationship is negative when the other variables are held constant. These relationships are statistically significant because the p values are all virtually zero. In summary, low access to food and more fast food decrease the mortality rate, and the presence of SNAP stores increases the mortality rate. According to the adjusted <span class="math inline">\(R^2\)</span> value, these factors only account for 26.5% of the variation in mortality rate. What accounts for the other 73.5% of the mortality rate? This model does not include enough other influential variables that are necessary to access the factors that lead to a high mortality rate.</strong></p>
</section>
<section id="mortality-contolling-for-state-differences" class="level3">
<h3 class="anchored" data-anchor-id="mortality-contolling-for-state-differences">Mortality, contolling for state differences</h3>
<p>RUN A MODEL with some number of plausible independent/explanatory variables. Include <code>state</code> as one of them</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add other explanatory variables here</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>model_with_state <span class="ot">&lt;-</span> <span class="fu">lm</span>(mortality_rate <span class="sc">~</span> pct_low_access_pop <span class="sc">+</span> state,</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>                       <span class="at">data =</span> food_health)</span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a><span class="co"># This table is 50+ rows long! While it might be interesting to see changes in</span></span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a><span class="co"># intercept in relation to Alaska (the omitted state here), like how Alabama's</span></span>
<span id="cb54-7"><a href="#cb54-7" aria-hidden="true" tabindex="-1"></a><span class="co"># mortality rate is 137 higher than Alaska's while DC's is 84 lower, it's not</span></span>
<span id="cb54-8"><a href="#cb54-8" aria-hidden="true" tabindex="-1"></a><span class="co"># super helpful. Controlling for state does capture some of the state-specific</span></span>
<span id="cb54-9"><a href="#cb54-9" aria-hidden="true" tabindex="-1"></a><span class="co"># reasons for varying mortality though, so it's good to include. We just don't</span></span>
<span id="cb54-10"><a href="#cb54-10" aria-hidden="true" tabindex="-1"></a><span class="co"># really need to see all those coefficients. To remove them from this table of</span></span>
<span id="cb54-11"><a href="#cb54-11" aria-hidden="true" tabindex="-1"></a><span class="co"># results, filter them out. The "!" in R means "not", so here we're only looking</span></span>
<span id="cb54-12"><a href="#cb54-12" aria-hidden="true" tabindex="-1"></a><span class="co"># at rows that don't start with "state"</span></span>
<span id="cb54-13"><a href="#cb54-13" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(model_with_state, <span class="at">conf.int =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb54-14"><a href="#cb54-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">str_starts</span>(term, <span class="st">"state"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 7
  term               estimate std.error statistic   p.value conf.low conf.high
  &lt;chr&gt;                 &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)           835.       23.3     35.9  8.30e-236    790.      881. 
2 pct_low_access_pop    -54.7      12.1     -4.50 6.95e-  6    -78.5     -30.9</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>model_mortality_many_state <span class="ot">&lt;-</span> <span class="fu">lm</span>(mortality_rate <span class="sc">~</span> pct_low_access_pop <span class="sc">+</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>                                            snap_stores_per_1000 <span class="sc">+</span></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>                                            fastfood_per_1000 <span class="sc">+</span></span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>                                            per_dem_2016 <span class="sc">+</span></span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a>                                            state,</span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a>                           <span class="at">data =</span> food_health)</span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(model_mortality_many_state, <span class="at">conf.int =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb56-9"><a href="#cb56-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">str_starts</span>(term, <span class="st">"state"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 7
  term                 estimate std.error statistic   p.value conf.low conf.high
  &lt;chr&gt;                   &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)             652.      24.0      27.2  8.32e-146    605.     699.  
2 pct_low_access_pop      -97.2     11.6      -8.39 7.08e- 17   -120.     -74.5 
3 snap_stores_per_1000    135.       5.68     23.7  5.34e-114    123.     146.  
4 fastfood_per_1000       -17.0      6.72     -2.52 1.17e-  2    -30.1     -3.78
5 per_dem_2016            -63.9     15.5      -4.13 3.65e-  5    -94.2    -33.6 </code></pre>
</div>
</div>
<p><strong>When controlling for low access to food, the number of SNAP stores per 1000 residents, the prevalence of fast food restaurants, and state, as the percent of the county who voted Democrat in 2016 increases by one point, the mortality rate decreases by 63.88 (per 100,000 residents), which is less of a decrease than without controlling for state. As the percent of residents with low access to food increases, the mortality rate still decreases when holding all other variables constant, but by much less. The prevalence of SNAP stores still has a positive relationship with the mortality rate, and the prevalence of fast food restaurants’ relationship is still negative when the other variables are held constant, but there is less of a difference. These relationships are still statistically significant because the p values are all virtually zero. In summary, low access to food and more fast food decrease the mortality rate, and the presence of SNAP stores increases the mortality rate, but less so when you control for state.</strong></p>
</section>
</section>
<section id="all-models-at-the-same-time-1" class="level2">
<h2 class="anchored" data-anchor-id="all-models-at-the-same-time-1">All models at the same time</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Right now there are only two models here. Add the others from above (whatever </span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a><span class="co"># you called them) like so: </span></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a><span class="co"># modelsummary(list(model_mortality_food, some_other_model, yet_another_model, etc))</span></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Also, by default, modelsummary will include all the state coefficients, which</span></span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a><span class="co"># we don't want. We can omit specific coefficients with the `coef_omit`</span></span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a><span class="co"># argument. The ^ character means it'll omit coefficients that *start with*</span></span>
<span id="cb58-8"><a href="#cb58-8" aria-hidden="true" tabindex="-1"></a><span class="co"># "state". Without ^, it would omit any coefficient where the characters "state"</span></span>
<span id="cb58-9"><a href="#cb58-9" aria-hidden="true" tabindex="-1"></a><span class="co"># appeared anywhere in the name, which might be too greedy</span></span>
<span id="cb58-10"><a href="#cb58-10" aria-hidden="true" tabindex="-1"></a>notes <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"t statistics in parentheses</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb58-11"><a href="#cb58-11" aria-hidden="true" tabindex="-1"></a>           <span class="st">"+ p &lt; 0.1, * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001"</span>)</span>
<span id="cb58-12"><a href="#cb58-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-13"><a href="#cb58-13" aria-hidden="true" tabindex="-1"></a><span class="fu">modelsummary</span>(<span class="fu">list</span>(<span class="st">"Model 1"</span><span class="ot">=</span>model_snap,</span>
<span id="cb58-14"><a href="#cb58-14" aria-hidden="true" tabindex="-1"></a>                  <span class="st">"Model 2"</span><span class="ot">=</span>model_vote,</span>
<span id="cb58-15"><a href="#cb58-15" aria-hidden="true" tabindex="-1"></a>                  <span class="st">"Model 3"</span><span class="ot">=</span>model_mortality_food,</span>
<span id="cb58-16"><a href="#cb58-16" aria-hidden="true" tabindex="-1"></a>                  <span class="st">"Model 4"</span><span class="ot">=</span>model_mortality_snap,</span>
<span id="cb58-17"><a href="#cb58-17" aria-hidden="true" tabindex="-1"></a>                  <span class="st">"Model 5"</span><span class="ot">=</span>model_mortality_many,</span>
<span id="cb58-18"><a href="#cb58-18" aria-hidden="true" tabindex="-1"></a>                  <span class="st">"Model 6"</span><span class="ot">=</span>model_with_state,</span>
<span id="cb58-19"><a href="#cb58-19" aria-hidden="true" tabindex="-1"></a>                  <span class="st">"Model 7"</span><span class="ot">=</span>model_mortality_many_state),</span>
<span id="cb58-20"><a href="#cb58-20" aria-hidden="true" tabindex="-1"></a>             <span class="at">coef_omit =</span> <span class="st">"^state"</span>,</span>
<span id="cb58-21"><a href="#cb58-21" aria-hidden="true" tabindex="-1"></a>             <span class="at">coef_rename =</span> <span class="fu">c</span>(<span class="at">pct_low_access_pop =</span> <span class="st">"Percent of the county's population with low access to food"</span>, </span>
<span id="cb58-22"><a href="#cb58-22" aria-hidden="true" tabindex="-1"></a>                             <span class="at">snap_stores_per_1000 =</span> <span class="st">"Number of stores that accept SNAP in a county (per 1,000 residents)"</span>, </span>
<span id="cb58-23"><a href="#cb58-23" aria-hidden="true" tabindex="-1"></a>                             <span class="at">fastfood_per_1000 =</span> <span class="st">"Number of fast food stores in a county (per 1,000 residents"</span>, </span>
<span id="cb58-24"><a href="#cb58-24" aria-hidden="true" tabindex="-1"></a>                             <span class="at">per_dem_2016 =</span> <span class="st">"Percent of the county that voted for Clinton in 2016"</span>),</span>
<span id="cb58-25"><a href="#cb58-25" aria-hidden="true" tabindex="-1"></a>             <span class="at">output =</span> <span class="st">"kableExtra"</span>,</span>
<span id="cb58-26"><a href="#cb58-26" aria-hidden="true" tabindex="-1"></a>             <span class="at">estimate =</span> <span class="st">"{estimate} {stars}"</span>,</span>
<span id="cb58-27"><a href="#cb58-27" aria-hidden="true" tabindex="-1"></a>             <span class="at">statistic =</span> <span class="st">"statistic"</span>,</span>
<span id="cb58-28"><a href="#cb58-28" aria-hidden="true" tabindex="-1"></a>             <span class="at">title =</span> <span class="st">"Mortality Rates and Access to Food"</span>,</span>
<span id="cb58-29"><a href="#cb58-29" aria-hidden="true" tabindex="-1"></a>             <span class="at">fmt =</span>  <span class="dv">2</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb58-30"><a href="#cb58-30" aria-hidden="true" tabindex="-1"></a>    <span class="fu">row_spec</span>(<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>,<span class="dv">5</span>,<span class="dv">7</span>,<span class="dv">9</span>), <span class="at">background =</span> <span class="st">"#f7fabe"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb58-31"><a href="#cb58-31" aria-hidden="true" tabindex="-1"></a>    <span class="fu">footnote</span>(<span class="at">general =</span> notes, <span class="at">footnote_as_chunk =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;border-bottom: 0;">
<caption>Mortality Rates and Access to Food</caption>
 <thead>
  <tr>
   <th style="text-align:left;">   </th>
   <th style="text-align:center;"> Model 1 </th>
   <th style="text-align:center;"> &nbsp;Model 2 </th>
   <th style="text-align:center;"> &nbsp;Model 3 </th>
   <th style="text-align:center;"> &nbsp;Model 4 </th>
   <th style="text-align:center;"> &nbsp;Model 5 </th>
   <th style="text-align:center;"> &nbsp;Model 6 </th>
   <th style="text-align:center;"> &nbsp;Model 7 </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;background-color: #f7fabe !important;"> (Intercept) </td>
   <td style="text-align:center;background-color: #f7fabe !important;"> 654.37 *** </td>
   <td style="text-align:center;background-color: #f7fabe !important;"> 861.34 *** </td>
   <td style="text-align:center;background-color: #f7fabe !important;"> 845.31 *** </td>
   <td style="text-align:center;background-color: #f7fabe !important;"> 654.37 *** </td>
   <td style="text-align:center;background-color: #f7fabe !important;"> 743.85 *** </td>
   <td style="text-align:center;background-color: #f7fabe !important;"> 835.29 *** </td>
   <td style="text-align:center;background-color: #f7fabe !important;"> 651.97 *** </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:center;"> (103.05) </td>
   <td style="text-align:center;"> (142.43) </td>
   <td style="text-align:center;"> (208.42) </td>
   <td style="text-align:center;"> (103.05) </td>
   <td style="text-align:center;"> (83.41) </td>
   <td style="text-align:center;"> (35.89) </td>
   <td style="text-align:center;"> (27.18) </td>
  </tr>
  <tr>
   <td style="text-align:left;background-color: #f7fabe !important;"> Number of stores that accept SNAP in a county (per 1,000 residents) </td>
   <td style="text-align:center;background-color: #f7fabe !important;"> 174.49 *** </td>
   <td style="text-align:center;background-color: #f7fabe !important;">  </td>
   <td style="text-align:center;background-color: #f7fabe !important;">  </td>
   <td style="text-align:center;background-color: #f7fabe !important;"> 174.49 *** </td>
   <td style="text-align:center;background-color: #f7fabe !important;"> 181.28 *** </td>
   <td style="text-align:center;background-color: #f7fabe !important;">  </td>
   <td style="text-align:center;background-color: #f7fabe !important;"> 134.63 *** </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:center;"> (27.71) </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> (27.71) </td>
   <td style="text-align:center;"> (29.92) </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> (23.69) </td>
  </tr>
  <tr>
   <td style="text-align:left;background-color: #f7fabe !important;"> Percent of the county that voted for Clinton in 2016 </td>
   <td style="text-align:center;background-color: #f7fabe !important;">  </td>
   <td style="text-align:center;background-color: #f7fabe !important;"> −139.35 *** </td>
   <td style="text-align:center;background-color: #f7fabe !important;">  </td>
   <td style="text-align:center;background-color: #f7fabe !important;">  </td>
   <td style="text-align:center;background-color: #f7fabe !important;"> −149.20 *** </td>
   <td style="text-align:center;background-color: #f7fabe !important;">  </td>
   <td style="text-align:center;background-color: #f7fabe !important;"> −63.88 *** </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> (−8.13) </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> (−9.82) </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> (−4.13) </td>
  </tr>
  <tr>
   <td style="text-align:left;background-color: #f7fabe !important;"> Percent of the county's population with low access to food </td>
   <td style="text-align:center;background-color: #f7fabe !important;">  </td>
   <td style="text-align:center;background-color: #f7fabe !important;">  </td>
   <td style="text-align:center;background-color: #f7fabe !important;"> −124.52 *** </td>
   <td style="text-align:center;background-color: #f7fabe !important;">  </td>
   <td style="text-align:center;background-color: #f7fabe !important;"> −170.35 *** </td>
   <td style="text-align:center;background-color: #f7fabe !important;"> −54.66 *** </td>
   <td style="text-align:center;background-color: #f7fabe !important;"> −97.19 *** </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> (−9.23) </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> (−13.89) </td>
   <td style="text-align:center;"> (−4.50) </td>
   <td style="text-align:center;"> (−8.39) </td>
  </tr>
  <tr>
   <td style="text-align:left;background-color: #f7fabe !important;"> Number of fast food stores in a county (per 1,000 residents </td>
   <td style="text-align:center;background-color: #f7fabe !important;">  </td>
   <td style="text-align:center;background-color: #f7fabe !important;">  </td>
   <td style="text-align:center;background-color: #f7fabe !important;">  </td>
   <td style="text-align:center;background-color: #f7fabe !important;">  </td>
   <td style="text-align:center;background-color: #f7fabe !important;"> −17.62 * </td>
   <td style="text-align:center;background-color: #f7fabe !important;">  </td>
   <td style="text-align:center;background-color: #f7fabe !important;"> −16.96 * </td>
  </tr>
  <tr>
   <td style="text-align:left;box-shadow: 0px 1px">  </td>
   <td style="text-align:center;box-shadow: 0px 1px">  </td>
   <td style="text-align:center;box-shadow: 0px 1px">  </td>
   <td style="text-align:center;box-shadow: 0px 1px">  </td>
   <td style="text-align:center;box-shadow: 0px 1px">  </td>
   <td style="text-align:center;box-shadow: 0px 1px"> (−2.29) </td>
   <td style="text-align:center;box-shadow: 0px 1px">  </td>
   <td style="text-align:center;box-shadow: 0px 1px"> (−2.52) </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Num.Obs. </td>
   <td style="text-align:center;"> 3112 </td>
   <td style="text-align:center;"> 3135 </td>
   <td style="text-align:center;"> 3116 </td>
   <td style="text-align:center;"> 3112 </td>
   <td style="text-align:center;"> 3093 </td>
   <td style="text-align:center;"> 3116 </td>
   <td style="text-align:center;"> 3093 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> R2 </td>
   <td style="text-align:center;"> 0.198 </td>
   <td style="text-align:center;"> 0.021 </td>
   <td style="text-align:center;"> 0.027 </td>
   <td style="text-align:center;"> 0.198 </td>
   <td style="text-align:center;"> 0.266 </td>
   <td style="text-align:center;"> 0.384 </td>
   <td style="text-align:center;"> 0.488 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> R2 Adj. </td>
   <td style="text-align:center;"> 0.198 </td>
   <td style="text-align:center;"> 0.020 </td>
   <td style="text-align:center;"> 0.026 </td>
   <td style="text-align:center;"> 0.198 </td>
   <td style="text-align:center;"> 0.265 </td>
   <td style="text-align:center;"> 0.374 </td>
   <td style="text-align:center;"> 0.479 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> AIC </td>
   <td style="text-align:center;"> 39196.3 </td>
   <td style="text-align:center;"> 40180.0 </td>
   <td style="text-align:center;"> 39901.5 </td>
   <td style="text-align:center;"> 39196.3 </td>
   <td style="text-align:center;"> 38673.5 </td>
   <td style="text-align:center;"> 38576.6 </td>
   <td style="text-align:center;"> 37658.7 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BIC </td>
   <td style="text-align:center;"> 39214.4 </td>
   <td style="text-align:center;"> 40198.1 </td>
   <td style="text-align:center;"> 39919.6 </td>
   <td style="text-align:center;"> 39214.4 </td>
   <td style="text-align:center;"> 38709.8 </td>
   <td style="text-align:center;"> 38897.0 </td>
   <td style="text-align:center;"> 37996.8 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Log.Lik. </td>
   <td style="text-align:center;"> −19595.130 </td>
   <td style="text-align:center;"> −20086.999 </td>
   <td style="text-align:center;"> −19947.736 </td>
   <td style="text-align:center;"> −19595.130 </td>
   <td style="text-align:center;"> −19330.772 </td>
   <td style="text-align:center;"> −19235.313 </td>
   <td style="text-align:center;"> −18773.354 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> RMSE </td>
   <td style="text-align:center;"> 131.33 </td>
   <td style="text-align:center;"> 146.70 </td>
   <td style="text-align:center;"> 145.88 </td>
   <td style="text-align:center;"> 131.33 </td>
   <td style="text-align:center;"> 125.32 </td>
   <td style="text-align:center;"> 116.06 </td>
   <td style="text-align:center;"> 104.66 </td>
  </tr>
</tbody>
<tfoot><tr><td style="padding: 0; " colspan="100%">
<span style="font-style: italic;">Note: </span> <sup></sup> t statistics in parentheses<br> <sup></sup> + p &lt; 0.1, * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001</td></tr></tfoot>
</table>

</div>
</div>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>