---
title: "Daily Symptoms Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(ggrepel) 
library(scales)

# Load data here
set.seed(80085)
colors <- c("#7400CC", "#CC0AA4", "#0E0ACC", "#3ACC14", 
            "#CCAC14", "#0ACCC5", "#CC5514")

colors2 <- c("#CCAC14", "#0ACCC5", "#CC5514", 
             "#3ACC14", "#0E0ACC", "#CC0AA4", "#7400CC")

sym <- read_csv("data/symptoms.csv") %>% 
  rename(overall = `overall pain`,
         forearm = `forearm pain`,
         back = `back pain`) %>% 
  mutate(date = mdy(date)) %>%
  mutate(swim = ifelse(Swimming == "Yes", 1, 0)) %>% 
  mutate(si = ifelse(`suicidal ideation` == "yes", 1, 0),
         night = ifelse(nightmares == "yes", 1, 0))

```

## Row {data-height="600"}

### Daily Symptoms - Interactive

```{r dailys}

sym1 <- sym %>% 
  pivot_longer(c(overall, forearm, back, fatigue, mood, anxiety, focus)) %>% 
  pivot_longer(c(si, night, swim), 
               names_to = "points", 
               values_to = "point_value") %>% 
  mutate(sym_label = case_when(name == "overall" ~ "Overall pain",
                               name == "forearm" ~ "Forearm pain",
                               name == "back" ~ "Back pain",
                               name == "fatigue" ~ "Fatigue",
                               name == "mood" ~ "Depression",
                               name == "anxiety" ~ "Anxiety",
                               name == "focus" ~ "Focus Issues"),
         dummies = case_when(points == "si" ~ "S.I.",
                             points == "night" ~ "Nightmares",
                             points == "swim" ~ "Swimming")) %>% 
  mutate(tip_line = paste0(format(date, "%b %e"), 
                           "<br>", sym_label, 
                           " - ", value),
         tip_point = paste0(dummies, 
                            "<br>", format(date, "%b %e"), 
                            " (Overall pain - ", value, ")"))

symplot <- sym1 %>% 
  ggplot() +
  geom_line(aes(date, value, 
                color = sym_label,
                linetype = sym_label), 
            linewidth = 1) +
  geom_point(aes(date, value, 
                 color = sym_label,
                 text = tip_line), 
             size = .1) +
  geom_point(data = sym1 %>% filter(point_value == 1, name == "overall"), 
             aes(date, case_when(dummies == "Nightmares" ~ 1.85,
                                 dummies == "S.I." ~ 1.4,
                                 dummies == "Swimming" ~ .95),
                 fill = dummies,
                 text = tip_point),
             size = 3, alpha = .75) +
  scale_x_date(breaks = date_breaks(width = "1 week"),
               labels = date_format("%b %e"),
               expand = c(.01,.01)) +
  scale_y_continuous(breaks = seq(0,10,2)) +
  scale_color_manual(values = colors,
                     limits = c("Overall pain", "Forearm pain", 
                                "Back pain", "Fatigue",
                                "Depression", "Anxiety", "Focus Issues")) +
  scale_linetype_manual(values = c("solid", "twodash", 
                                   "twodash", "twodash", 
                                   "twodash", "twodash", "twodash"), 
                        limits = c("Overall pain", "Forearm pain", 
                                   "Back pain", "Fatigue",
                                   "Depression", "Anxiety", "Focus Issues")) +
  scale_fill_manual(values = c("#456699", "#CC341F", "#0CEBFF")) +
  scale_shape_manual(values = c(21,22,23)) +
  labs(x = NULL,
       y = "Severity Level",
       color = NULL,
       fill = NULL,
       linetype = NULL,
       title = "Daily Symptoms") +
  theme_light() +
  theme(panel.border = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = "#9DDD99"),
        axis.text = element_text(color = "#310873",
                                 family = "serif"),
        axis.title = element_text(color = "#310873"),
        axis.ticks = element_blank(),
        plot.title = element_text(color = "#310873",
                                  size = 14,
                                  face = "bold"))

p <- ggplotly(symplot, tooltip = "text") 

p$x$data[[1]]$legendgroup <- p$x$data[[1]]$name
p$x$data[[1]]$name <- "Anxiety"
p$x$data[[2]]$legendgroup <- p$x$data[[2]]$name
p$x$data[[2]]$name <- "Back Pain"
p$x$data[[3]]$legendgroup <- p$x$data[[3]]$name
p$x$data[[3]]$name <- "Depression"
p$x$data[[4]]$legendgroup <- p$x$data[[4]]$name
p$x$data[[4]]$name <- "Fatigue"
p$x$data[[5]]$legendgroup <- p$x$data[[5]]$name
p$x$data[[5]]$name <- "Focus Issues"
p$x$data[[6]]$legendgroup <- p$x$data[[6]]$name
p$x$data[[6]]$name <- "Forearm pain"
p$x$data[[7]]$legendgroup <- p$x$data[[7]]$name
p$x$data[[7]]$name <- "Overall Pain"

p$x$data[[15]]$legendgroup <- p$x$data[[15]]$name
p$x$data[[15]]$name <- "Nightmares"
p$x$data[[16]]$legendgroup <- p$x$data[[16]]$name
p$x$data[[16]]$name <- "S.I."
p$x$data[[17]]$legendgroup <- p$x$data[[17]]$name
p$x$data[[17]]$name <- "Swimming"

p

```

## Row {data-height="400"}

### Physical Pain (Previous 30 Days)

```{r pain, fig.width=7, fig.height=3.5}

pain <- sym %>% 
  pivot_longer(c(overall, forearm, back, fatigue)) 

pain %>% 
  filter(date > (today() - 30)) %>% 
  ggplot(aes(color = name)) +
  geom_line(aes(date, value, 
                linetype = name), 
            linewidth = 1) +
  geom_point(data = sym %>% filter(Swimming == "Yes", date > (today() - 30)), 
             aes(date, overall,
                 shape = Swimming),
             color = "#0E0ACC", 
             fill = "#0CEBFF", 
             size = 5.5) +
  scale_x_date(breaks = date_breaks(width = "1 week"),
               labels = date_format("%b %d"),
               expand = c(.01,.01)) +
  scale_y_continuous(breaks = seq(0,10,2),
                     limits = c(1,10)) +
  scale_color_manual(values = colors,
                     limits = c("overall", "forearm", 
                                "back", "fatigue"),
                     labels = c("Overall pain", "Forearm pain", 
                                "Back pain", "Fatigue")) +
  scale_linetype_manual(values = c("solid", "twodash", 
                                   "twodash", "twodash"), 
                        limits = c("overall", "forearm", 
                                   "back", "fatigue"),
                        labels = c("Overall pain", "Forearm pain", 
                                   "Back pain", "Fatigue")) +
  scale_shape_manual(values = 21,
                     labels = "Swimming") +
  labs(x = NULL,
       y = "Pain Level",
       color = NULL,
       linetype = NULL,
       shape = NULL,
       title = "Daily Physical Pain") +
  theme_light() +
  theme(panel.border = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = "#3ACC14", 
                                          linetype = "dotted"),
        panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_line(color = "#9DDD99", 
                                          linetype = "dotted"),
        axis.text = element_text(color = "#310873", 
                                 family = "serif"),
        axis.title = element_text(color = "#310873", 
                                  family = "sans"),
        axis.ticks = element_blank(),
        plot.title = element_text(color = "#310873", 
                                  size = 14, 
                                  face = "bold"),
        legend.position = "bottom",
        legend.text = element_text(color = "#310873", 
                                   family = "sans"))

```

### Mental Health (Previous 30 Days)

```{r mental, fig.width=7, fig.height=3.5}

mental <- sym %>% 
  pivot_longer(c(mood, anxiety, focus, fatigue)) 

mental %>% 
  filter(date > as.Date("2023-06-16")) %>% 
  ggplot(aes(color = name)) +
  geom_line(aes(date, value), linewidth = 1, linetype = "twodash") +
  geom_point(data = sym %>% filter(night == 1, date > (today() - 30)), 
             aes(date, mood,
                 shape = "night"),
             color = "#0E0ACC", 
             fill = "#456699", 
             size = 5.5) +
  scale_x_date(breaks = date_breaks(width = "1 week"),
               labels = date_format("%b %d"),
               expand = c(.01,.01)) +
  scale_y_continuous(breaks = seq(0,10,2),
                     limits = c(1,10)) +
  scale_color_manual(values = colors2,
                     limits = c("mood", "anxiety", 
                                "focus", "fatigue"),
                     labels = c("Depression", "Anxiety", 
                                "Focus Issues", "Fatigue")) +
  scale_shape_manual(values = 21,
                     labels = "NIghtmares") +
  labs(x = NULL,
       y = "Severity Level",
       color = NULL,
       shape = NULL,
       title = "Daily Mental Health") +
  theme_light() +
  theme(panel.border = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = "#3ACC14", 
                                          linetype = "dotted"),
        panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_line(color = "#9DDD99", 
                                          linetype = "dotted"),
        axis.text = element_text(color = "#310873", 
                                 family = "serif"),
        axis.title = element_text(color = "#310873", 
                                  family = "sans"),
        axis.ticks = element_blank(),
        plot.title = element_text(color = "#310873", 
                                  size = 14, 
                                  face = "bold"),
        legend.position = "bottom",
        legend.text = element_text(color = "#310873", 
                                   family = "sans"))


```
